# Secrets:
# RELEASE_TOKEN = write permission token

name: build

on:
  workflow_dispatch:
  push: { branches: [ main ] }

jobs:
  build:

    strategy:
      matrix:
        include:
          - arch: i686
            platform: 386
            runner: ubuntu-24.04
          - arch: x86_64
            platform: amd64
            runner: ubuntu-24.04
          - arch: aarch64
            platform: arm64
            runner: ubuntu-24.04-arm

    runs-on: ${{ matrix.runner }}
    env:
      DEST: /opt/packelf
      arch: ${{ matrix.arch }}
      platform: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4

    - name: Debian ${{ matrix.arch }}
      run: |
        mkdir "${arch}"
        sed -i 's|\${dest}|'"${DEST:?}"'|g' ./debian/*.sh
        pkg="$( grep -hoP '^pkg=\(\K[^)]+' ./debian/*.sh )"
        printf '%s\n' 'FROM debian:trixie-slim' 'COPY debian.sh /root/' 'RUN apt-get update && apt-get upgrade -y && apt-get install -y patchelf '"$(echo ${pkg})" |
        podman build --platform=linux/"${platform}" -f /dev/stdin -t worker-debian .
        podman run --volume=./"${arch}":/result --volume=./debian:/workdir --workdir=/workdir -i worker-debian /root/debian.sh

    - name: Alpine ${{ matrix.arch }}
      run: |
        sed -i 's|\${dest}|'"${DEST:?}/static"'|g' ./alpine/*.sh
        pkg="$( sed -n '/apk add .*\\$/{n;p}' ./alpine/*.sh )"
        printf '%s\n' 'FROM alpine' 'RUN apk add bash build-base patchelf '"$(echo ${pkg})" |
        podman build --platform=linux/"${platform}" -f /dev/stdin -t worker-alpine .
        podman run --volume=./"${arch}":/result --volume=./alpine:/workdir --workdir=/workdir worker-alpine bash -c 'for i in ./*.sh; do "${i}"; done'

    - name: Release result
      env:
        GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
      run: |
        ( cd "${arch}"; tar --numeric-owner --owner=0 --group=0 -czf ../"${arch}".tar.gz * )
        ! gh release view result &>/dev/null &&
        gh release create result "${arch}".tar.gz -n 'download here' ||
        gh release upload result "${arch}".tar.gz --clobber
